# Generated by Django 6.0.1 on 2026-03-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('react', 'React'), ('php', 'PHP')], default='other', max_length=50),
        ),
    ]
