# Generated by Django 6.0.3 on 2026-03-27 07:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('react', 'React'), ('php', 'PHP'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
