# Generated by Django 6.0.3 on 2026-03-27 08:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_alter_course_category_alter_course_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='file'),
        ),
    ]
